# see https://pre-commit.com

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args:
          - '--maxkb=512'
      - id: check-json
      - id: check-yaml
      - id: detect-aws-credentials
        args:
          - '--allow-missing-credentials'
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - '--fix=lf'
      - id: trailing-whitespace

  # yamllint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint

  # cspell
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.8.2
    hooks:
      - id: cspell
